name: build-macos-binary

on:
  push:
    tags:
      - '*'

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      binary_name: geopackage-optimizer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.8'

      - name: Set up version
        id: get_version
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=dev" >> $GITHUB_OUTPUT
          fi

      - name: Sanitize ref name
        id: sanitize_ref
        shell: bash
        run: |
          ref="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
          sanitized=$(echo "$ref" | tr '/\\' '__')
          echo "sanitized_ref=$sanitized" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.sanitize_ref.outputs.sanitized_ref || github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install dependencies
        run: |
          brew install sqlite libspatialite

      - name: Build macOS binary
        run: |
          export CGO_ENABLED=1
          export GOOS=darwin
          export GOARCH=${{ matrix.arch }}
          go build -o ${{ env.binary_name }}-${{ steps.get_version.outputs.version }}-darwin-${{ matrix.arch }}

      - name: Zip binary
        run: |
          zip ${{ env.binary_name }}-${{ steps.get_version.outputs.version }}-darwin-${{ matrix.arch }}.zip ${{ env.binary_name }}-${{ steps.get_version.outputs.version }}-darwin-${{ matrix.arch }}

      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.binary_name }}-${{ steps.get_version.outputs.version }}-darwin-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
